# Generated by Django 4.0.6 on 2022-07-22 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
