# Generated by Django 4.1 on 2022-08-03 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0012_post_updated_by_post_updated_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subscribe',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
