# Generated by Django 4.1 on 2022-08-03 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0013_category_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subscribe',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
