# Generated by Django 4.0.6 on 2022-08-05 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0015_post_dislike_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subscribe',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
